name: Build-NextPad
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build App
        run: |
          xcodebuild -project NextPad.xcodeproj \
                     -scheme NextPad \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: NextPad-App
          path: |
            build/Build/Products/Release/*.app
            ./*.app
